### ISSUE TITLE
Suggestion for README

### ISSUE THREAD

**Issue by Zamiell** [KeitIG/teeny-conf#1]
Great library, thanks.

One thing I noticed about the library is that it is missing a `config.delete()` method. Shouldn't that exist?

Failing the implementation of that, please add a note to the README that demonstrates how to delete a value from the JSON file, like so:

```
config.set('foo', undefined);
config.saveSync();
```

**Comment by KeitIG** [comment]
That's so stupid I feed bad. I'll implement that asap.

**Comment by Zamiell** [comment]
LOL

I found this library from your StackOverflow post about not storing crap in localStorage when using Electron, so thanks again for the work.

**Comment by KeitIG** [comment]
Fixed in 1.1.0 :]
